apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  namespace: bookstore
  labels:
    app: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      annotations:
        metrics.dynatrace.com/path: /stats/prometheus
        metrics.dynatrace.com/port: "15020"
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/secure: "false"
      namespace: bookstore
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore
          image: ivangudak096/bookstore-webapp-{ARCH}:latest
          ports:
            - containerPort: 4200
          env:
            - name: DT_ACTIVE_WEB_ENV
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: web_app_profile
            - name:   BOOKSTORE_BASE_SRV_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: services_ext_url
            - name:   AGENT
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: web_agent
            - name:   TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: tenant_id
            - name: TENANT_LAYER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: tenant_layer
            - name: TENANT_URL
              value: "https://$(TENANT_ID).$(TENANT_LAYER).dynatracelabs.com"
            - name: OA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: oneagent-token
            - name: OTEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: otel-token
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-svc
  namespace: bookstore
spec:
  selector:
    app: bookstore
  type: LoadBalancer # ClusterIP
  ports:
    - port: 90
      protocol: TCP
      targetPort: 4200
      nodePort: 30000 # comment if ClusterIP
