apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-ingress
  namespace: bookstore
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - path: /ingest(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ingest-svc
                port:
                  number: 89
          - path: /clients
            pathType: Prefix
            backend:
              service:
                name: clients-svc
                port:
                  number: 81
          - path: /books
            pathType: Prefix
            backend:
              service:
                name: books-svc
                port:
                  number: 82
          - path: /carts
            pathType: Prefix
            backend:
              service:
                name: carts-svc
                port:
                  number: 83
          - path: /storage
            pathType: Prefix
            backend:
              service:
                name: storage-svc
                port:
                  number: 84
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: orders-svc
                port:
                  number: 85
          - path: /ratings
            pathType: Prefix
            backend:
              service:
                name: ratings-svc
                port:
                  number: 88
          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: payments-svc
                port:
                  number: 86
          - path: /superpay
            pathType: Prefix
            backend:
              service:
                name: superpay-svc
                port:
                  number: 87
          - path: /bookstore
            pathType: Prefix
            backend:
              service:
                name: bookstore-svc
                port:
                  number: 90
