= BookStore - Demo project
Ivan Gudak <ivan.gudak@dynatrace.com>
1.0, February 01, 2023: Kubernetes Deployment
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Bookstore project consists of 8 primary microservices, one web application, and load generator.
Purposes: demonstrating of Dynatrace capabilities in high-load and unhealthy environments

== Configuration
=== configmap
. Set your tenant's id and URL in *config.yaml*

    tenant_id: <tenant-id> ## for instance, fdg3423
    tenant_url: <url> ## e.g. https://fdg3423.sprint.dynatracelabs.com

. Define instrumentation (OneAgent or Otel) for the microservices in *config.yaml*

    <microservice>_agent: [oneAgent|otelAgent|none] # set for all *_agent records

. Generate Tokens
.. OpenIngest token
... Open Dynatrace UI > Manage > Access tokens
... click on *Generate new token*
... select *Ingest OpenTelemetry traces* in the scope
... click *Generate*
... convert the token to base64 (here is a Linux command):

    echo -n <token> | base64 -w 0
    # note: this will make a multiline output. Please concat all lines into a single one

.. OneAgent token
... Open Dynatrace UI > Manage > Access tokens
... click on *Generate new token*
... select *PaaS integration - Installer download* in the scope
... click *Generate*
... convert the token to base64 (here is a Linux command):

    echo -n <token> | base64 -w 0
    # note1: on MacOS -w 0 is not needed
    # note2: although the scope looks weird, there's no mistake.

. Put tokens in the secrets, *secret.yaml* file

    oneagent-token: <base64-ed OneAgent token (make sure you concatenated if it's multiline)>
    otel-token: <base64-ed Otel token (make sure you concatenated if it's multiline)>

=== deployment's yaml files
the yaml configurations for deployments need to be preconfigured.
Use preset_deployment.sh for that:

==== use preinstrumented images for Intel/AMD architecture:
```
./preset_deployment.sh -agents -x64
```

==== use preinstrumented images for ARMv8 architecture:
```
./preset_deployment.sh -agents -arm
```

==== use non-instrumented images for Intel/AMD architecture:
```
./preset_deployment.sh -noagent -x64
```

==== use non-instrumented images for ARMv8 architecture:
```
./preset_deployment.sh -noagent -arm
```

==== reset the yaml-files:
```
./preset_deployment.sh -reset
```

== Deployment
0. Create namespace:

    kubectl apply -f namespace.yaml

1. Create configmap:

    kubectl apply -f config.yaml


2. Create secrets:

    kubectl apply -f secret.yaml


3. Create databases:

    kubectl apply -f databases.yaml


4. Create all services:

    kubectl apply -f clients.yaml
    kubectl apply -f books.yaml
    kubectl apply -f carts.yaml
    kubectl apply -f storage.yaml
    kubectl apply -f orders.yaml
    kubectl apply -f ratings.yaml
    kubectl apply -f payments.yaml
    kubectl apply -f dynapay.yaml
    kubectl apply -f ingest.yaml


5. Create web app:

    kubectl apply -f bookstore.yaml




