= BookStore - Demo project
Ivan Gudak <ivan.gudak@dynatrace.com>
1.0, February 01, 2023: Kubernetes Deployment
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Bookstore project consists of 8 primary microservices, one web application, and load generator.
Purposes: demonstrating of Dynatrace capabilities in high-load and unhealthy environments

== Build

=== Prerequisite
. Docker service (docker desktop) should be running

=== Linux
. Go to k8s directory
. execute, optionally providing otel token with the scopes of trace_otel_ingest, log_otel_ingest, metric_otel_ingest
* #__the token can be base64-ed or open__#

    ./build_docker_all.sh [<tenantID>] [dev|sprint] [<otel_ingest_token>]

=== Windows
. Go to k8s directory
. execute, optionally providing otel token with the scopes of trace_otel_ingest, log_otel_ingest, metric_otel_ingest

    .\build_docker_all.bat [<tenantID>] [dev|sprint] [<otel_ingest_token>]


== Configuration
=== configmap
. Set your tenant's id and URL in *config.yaml*

    tenant_id: <tenant-id> ## for instance, fdg3423
    tenant_layer: <layer> ## e.g. sprint or dev

. Define instrumentation (OneAgent or Otel) for the microservices in *config.yaml*

    <microservice>_agent: [oneAgent|otelAgent|none] # set for all *_agent records

. Generate Tokens
.. OpenIngest token
... Open Dynatrace UI > Manage > Access tokens
... click on *Generate new token*
... select *Ingest OpenTelemetry traces* in the scope
... click *Generate*
... convert the token to base64 (here is a Linux command):

    echo -n <token> | base64 -w 0
    # note: this will make a multiline output. Please concat all lines into a single one

.. OneAgent token
... Open Dynatrace UI > Manage > Access tokens
... click on *Generate new token*
... select *PaaS integration - Installer download* in the scope
... click *Generate*
... convert the token to base64 (here is a Linux command):

    echo -n <token> | base64 -w 0
    # note1: on MacOS -w 0 is not needed
    # note2: although the scope looks weird, there's no mistake.

. Put tokens in the secrets, *secret.yaml* file

    oneagent-token: <base64-ed OneAgent token (make sure you concatenated if it's multiline)>
    otel-token: <base64-ed Otel token (make sure you concatenated if it's multiline)>

=== deployment's yaml files
the yaml configurations for deployments need to be preconfigured.
Use preset_deployment.sh for that:

==== "on-deploy agent installation" images for Intel/AMD architecture, books namespace (default ns is bookstore):
```
./preset_deployment.sh -gyes -ax64 -n books
```

==== "on-deploy agent installation"  images for ARMv8 architecture, books namespace (default ns is bookstore):
```
./preset_deployment.sh -gyes -aarm -n books
```

==== "on-build agent installation" images for Intel/AMD architecture, books namespace (default ns is bookstore):
```
./preset_deployment.sh -gpre -ax64 -n books
```

==== "on-build agent installation"  images for ARMv8 architecture, books namespace (default ns is bookstore):
```
./preset_deployment.sh -gpre -aarm -n books
```

==== use non-instrumented images for Intel/AMD architecture, bookstore namespace (-n to override):
```
./preset_deployment.sh -gno -ax64
```

==== use non-instrumented images for ARMv8 architecture, bookstore namespace (-n to override):
```
./preset_deployment.sh -gno -aarm
```

==== reset the yaml-files:
```
./preset_deployment.sh -reset
```

===== "on deploy" vs "on build":
. -gyes parameter makes OneAgent and Otel to be downloaded and configured on every pod start.
.. pros: you get the latest agent on every pod restart
.. cons: more traffic (download agents); more time for pod to start
. -gpre parameter makes OneAgent and Otel to be a part of docker image.
.. pros: quicker to start, less traffic (agent is already in the image)
.. cons: to update the Agents you need to rebuild the docker images

== Deployment
=== Manual deployment
0. Create namespace:

    kubectl apply -f namespace.yaml

1. Create configmap:

    kubectl apply -f config.yaml


2. Create secrets:

    kubectl apply -f secret.yaml


3. Create databases:

    kubectl apply -f databases.yaml


4. Create all services:

    kubectl apply -f clients.yaml
    kubectl apply -f books.yaml
    kubectl apply -f carts.yaml
    kubectl apply -f storage.yaml
    kubectl apply -f orders.yaml
    kubectl apply -f ratings.yaml
    kubectl apply -f payments.yaml
    kubectl apply -f dynapay.yaml
    kubectl apply -f ingest.yaml


5. Create web app:

    kubectl apply -f bookstore.yaml

6. Delete the app:

    kubectl delete -f bookstore.yaml
    kubectl delete -f clients.yaml
    kubectl delete -f books.yaml
    kubectl delete -f carts.yaml
    kubectl delete -f storage.yaml
    kubectl delete -f orders.yaml
    kubectl delete -f ratings.yaml
    kubectl delete -f payments.yaml
    kubectl delete -f dynapay.yaml
    kubectl delete -f ingest.yaml
    kubectl delete -f databases.yaml
    kubectl delete -f secret.yaml
    kubectl delete -f config.yaml
    kubectl delete -f namespace.yaml

=== Automated deployment

==== Linux

    ./restart.sh       # deploys databases and backend microservices
    ./restart.sh -web  # deploys everything including the web app
    ./restart.sh -nodb # won't touch the DB (restart of the DB causes data reset)
    ./delete.sh        # undeploys microservices and the web app (DBs stay)
    ./delete.sh -all   # undeploys everything, including the DBs, configmaps

==== Windows

==== Linux

    .\restart.bat       &REM deploys databases and backend microservices
    .\restart.bat -web  &REM deploys everything including the web app
    .\restart.bat -nodb &REM won't touch the DB (restart of the DB causes data reset)
    .\delete.bat        &REM undeploys microservices and the web app (DBs stay)
    .\delete.bat -all   &REM undeploys everything, including the DBs, configs
