# kubectl apply -f secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secret
  namespace: bookstore
type: Opaque
data:
  mysql-user-name: cm9vdA==
  mysql-user-pass: cEBzc3cwckQh
  pgdb-user-name: cGd1c2Vy
  pgdb-user-pass: cEBzc3cwckQh
  mongo-user-name: cm9vdA==
  mongo-user-pass: cEBzc3cwckQh
  mongo-user-pass-esc: cCU0MHNzdzByRCE=
  oneagent-token: <DT-Deployment-token>
  otel-token: <DT-openIngest-token>
