apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  namespace: bookstore
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      annotations:
        metrics.dynatrace.com/path: /stats/prometheus
        metrics.dynatrace.com/port: "15020"
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/secure: "false"
      namespace: bookstore
      labels:
        app: storage
        app.kubernetes.io/version: 1.5.0
        app.kubernetes.io/part-of: BookStore
    spec:
      containers:
        - name: storage
          image: ghcr.io/ihudak/storage-{AGENT}:latest
          ports:
            - containerPort: 8080
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: bookstore-configmap
            - secretRef:
                name: bookstore-secret
          env:
            - name: DT_RELEASE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: DT_RELEASE_BUILD_VERSION
              value: "2024-04-07-20:03:11"
            - name: DT_MYSQL_DBNAME
              value: none # DB NAME HERE
            - name: DT_PG_DBNAME
              value: dt_books_storage # DB NAME HERE
            - name:   AGENT
              valueFrom:
                configMapKeyRef:
                  name: bookstore-agents-configmap
                  key: storage_agent
            - name: TENANT_URL
              value: "https://$(TENANT_ID).$(TENANT_LAYER).dynatracelabs.com"
            - name: SERVICE_NAME
              value: Storage
            - name: SERVICE_FULL_NAME
              value: "$(APP_NAME).$(SERVICE_NAME).$(SVC_SUFFIX)"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "dt.security_context=$(SECURITY_CONTEXT),dt.cost.costcenter=$(COST_CENTER),dt.cost.project=$(COST_PROJECT),my.resource.attribute=$(MY_ATTR)"
          resources:
            limits:
              cpu: 300m
              memory: 768Mi
            requests:
              cpu: 300m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: storage-svc
  namespace: bookstore
spec:
  selector:
    app: storage
  type: LoadBalancer # ClusterIP
  ports:
    - name: http
      port: 84
      protocol: TCP
      targetPort: 8080
      nodePort: 30004 # comment if ClusterIP
    - name: debug
      port: 5004
      protocol: TCP
      targetPort: 5005
      nodePort: 32004 # comment if ClusterIP
