version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
