name: Docker Image CI ARM

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Deployment Environment'
        required: true
        default: 'arm64'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to docker repo
      run: echo $GH_TOKEN | docker login ghcr.io -u $GH_USER --password-stdin
      env:
        GH_USER: ${{ secrets.CR_USER }}
        GH_TOKEN: ${{ secrets.CR_PAT }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:noagent"
        push: true
        tags: ghcr.io/ihudak/java-noagent-arm64:latest,ghcr.io/ihudak/java-noagent-arm64:${{ github.run_number }}
        platforms: linux/arm64/v8
