name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Build noagent docker image
      working-directory: ./noagent
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/java-noagent-x64:latest
        docker push ghcr.io/ihudak/java-noagent-x64:latest

    - name: Build clients docker image
      working-directory: ./clients
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/clients-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/clients-noagent-x64:latest

    - name: Build books docker image
      working-directory: ./books
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/books-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/books-noagent-x64:latest

    - name: Build carts docker image
      working-directory: ./carts
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/carts-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/carts-noagent-x64:latest

    - name: Build storage docker image
      working-directory: ./storage
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/storage-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/storage-noagent-x64:latest

    - name: Build ratings docker image
      working-directory: ./ratings
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/ratings-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/ratings-noagent-x64:latest

    - name: Build orders docker image
      working-directory: ./orders
      run: | 
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/orders-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/orders-noagent-x64:latest

    - name: Build payments docker image
      working-directory: ./payments
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/payments-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/payments-noagent-x64:latest

    - name: Build dynapay docker image
      working-directory: ./dynapay
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/dynapay-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/dynapay-noagent-x64:latest

    - name: Build ingest docker image
      working-directory: ./ingest
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/ingest-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/ingest-noagent-x64:latest

    - name: Build WebApp Base docker image
      working-directory: ./web/base/noagent
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/node-angular-noagent-x64:latest
        docker push ghcr.io/ihudak/node-angular-noagent-x64:latest

    - name: Build web app image
      working-directory: ./web
      run: |
        docker build . --file Dockerfile --platform linux/amd64 --tag ihudak/web-noagent-x64:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg PLATFORM=x64 --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/web-noagent-x64:latest
      
