name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Login to docker repo
      run: echo $GH_TOKEN | docker login ghcr.io -u ihudak --password-stdin
      env:
        GH_TOKEN: ${{ secrets.CR_PAT }}
      
    - name: Build MySQL database
      working-directory: ./database/mysql
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/dt-mysql:latest
        docker push ghcr.io/ihudak/dt-mysql:latest

    - name: Build Postgresql database
      working-directory: ./database/pg
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/dt-postgres:latest
        docker push ghcr.io/ihudak/dt-postgres:latest
        
    - name: Build agents docker images
      working-directory: ./agents
      run: |
        rm ./env
        echo "DT_AGENT_DOWNLOAD_TENANT_URL=$DT_TENANT_URL" >> ./env
        echo "DT_AGENT_DOWNLOAD_TOKEN=$DT_TENANT_TOKEN" >> ./env
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/java-agents:latest --build-arg AGENTS_PRELOAD=false
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/java-preinstrument:latest --build-arg AGENTS_PRELOAD=true
        docker push ghcr.io/ihudak/java-agents:latest
        docker push ghcr.io/ihudak/java-preinstrument:latest
      env:
        DT_TENANT_TOKEN: ${{ secrets.DT_TENANT_TOKEN }}
        DT_TENANT_URL: ${{ secrets.DT_TENANT_URL }}


    - name: Build noagent docker image
      working-directory: ./noagent
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/java-noagent:latest
        docker push ghcr.io/ihudak/java-noagent:latest

    - name: Build clients docker image
      working-directory: ./clients
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/clients-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/clients-noagent:latest
        
    - name: Build books docker image
      working-directory: ./books
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/books-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/books-noagent:latest
        
    - name: Build carts docker image
      working-directory: ./carts
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/carts-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/carts-noagent:latest
        
    - name: Build storage docker image
      working-directory: ./storage
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/storage-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/storage-noagent:latest
        
    - name: Build ratings docker image
      working-directory: ./ratings
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/ratings-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/ratings-noagent:latest
        
    - name: Build orders docker image
      working-directory: ./orders
      run: | 
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/orders-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/orders-noagent:latest
        
    - name: Build payments docker image
      working-directory: ./payments
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/payments-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/payments-noagent:latest

    - name: Build dynapay docker image
      working-directory: ./dynapay
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/dynapay-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/dynapay-noagent:latest
        
    - name: Build ingest docker image
      working-directory: ./ingest
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/ingest-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/ingest-noagent:latest

    - name: Build WebApp Base docker image
      working-directory: ./web/base/noagent
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/node-angular-noagent:latest
        docker push ghcr.io/ihudak/node-angular-noagent:latest
        
    - name: Build web app image
      working-directory: ./web
      run: |
        docker build . --file Dockerfile --platform=linux/amd64,linux/arm64 --tag ghcr.io/ihudak/web-noagent:latest --build-arg BASE_REPO=ihudak --build-arg AGENT=noagent --build-arg BASE_IMG_TAG=latest
        docker push ghcr.io/ihudak/web-noagent:latest
      
